public enum BATTLESTATE
{
    NONE,
    INIT,
    UNITPLACE,
    UNITSELLECT,
    SHOWUNITDETAIL,
    ABILITYTARGET,
    MOVETARGET,
    SELECTSKILLTARGET,
    CONFIRMABILITYTARGET,
    MOVESEQUENCE,
    PERFORMABILITY
}